FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.prod.txt .
RUN pip install --no-cache-dir -r requirements.prod.txt

COPY . .

# Collect static files
RUN python manage.py collectstatic --noinput

EXPOSE 8000

# Run Gunicorn
CMD ["gunicorn", "tracking_site.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "4"]
