# Generated by Django 6.0.1 on 2026-01-20 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='created', max_length=32)),
                ('sender_name', models.CharField(blank=True, default='Smith Industries', max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('receiver_name', models.CharField(blank=True, default='Johnson & Co.', max_length=255)),
                ('receiver_email', models.EmailField(blank=True, max_length=254)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('package_description', models.CharField(blank=True, default='Electronic Components & Parts', max_length=255)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('dest_lat', models.FloatField(blank=True, null=True)),
                ('dest_lng', models.FloatField(blank=True, null=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='tracking_sh_trackin_27d25d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='tracking_sh_status_7032b0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='tracking_sh_created_10b593_idx'),
        ),
    ]
